version: '3.8'
services:
  zookeeper:
    networks:
      - kafka_network
    image: quay.io/debezium/zookeeper:2.7
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    networks:
      - kafka_network
    image: quay.io/debezium/kafka:2.7
    ports:
      - "9092:9092"  # For internal services
      - "29092:29092"  # For external connections from localhost
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
    depends_on:
      - zookeeper

  postgres:
    networks:
      - kafka_network
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    command: >
      postgres -c wal_level=logical
               -c max_replication_slots=4
               -c max_wal_senders=4

  connect:
    networks:
      - kafka_network
    image: quay.io/debezium/connect:2.7
    ports:
      - "8083:8083"
    environment:
      - GROUP_ID=1
      - BOOTSTRAP_SERVERS=kafka:9092
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - PLUGIN_NAME=pgoutput  # Specify the use of pgoutput
      - CONNECTOR_PLUGIN_PATH=/kafka/connect/plugins
    links:
      - zookeeper
      - kafka
      - postgres
    volumes:
      - ./kafka-plugins:/kafka/connect/plugins

  kafka-ui:
    networks:
      - kafka_network
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_SCHEMA_REGISTRY=http://schema-registry:8081
      - KAFKA_CLUSTERS_0_CONNECT=http://connect:8083
    depends_on:
      - zookeeper
      - kafka
      - connect

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge
